name: solar-system workflow
on: 
    workflow_dispatch:
    push:
        branches:
          - main
          - 'feature/*'
env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.username }}
    MONGO_PASSWORD: ${{ secrets.password }}
jobs: 
    unit-testing:
        name: unit-testing
        strategy:
            matrix:
                node-js-versions: [18,19,20]
                os: [ubuntu-latest,macos-latest]
                exclude:
                    - node-js-versions: 18
                      os: macos-latest
        runs-on: ${{ matrix.os }}
        steps:
          - name: checkout-repo
            uses: actions/checkout@v4
          - name: setup node
            uses: actions/setup-node@v6
            with: 
                node-version: ${{ matrix.node-js-versions }}
          - name: installing dependencies
            run: npm install
          - name: run unit tests
            run: npm test
          - name: save test results artifacts
            uses: actions/upload-artifact@v4
            with:
                name: results-${{ matrix.os }}-${{ matrix.node-js-versions }}
                path: test-results.xml